"use client";

import FeatureCard from "../ui/FeatureCard";

export default function FeatureSection() {
  return (
    <section className="mx-auto w-full max-w-7xl px-4 py-16 md:py-24 lg:py-40">
      
      {/* Heading */}
      <h2 className="inline-block w-fit bg-gradient-to-r from-[#19191D] to-[#626275] bg-clip-text text-4xl font-medium tracking-tight text-white lg:text-6xl">
        Four ways we make your <br className="hidden lg:block" />
        meetings better
      </h2>

      {/* Cards */}
      <div className="mt-16 grid snap-x snap-mandatory auto-cols-[80%] grid-flow-col gap-6 overflow-x-auto lg:grid-flow-row lg:grid-cols-2 lg:overflow-visible">
        
        <FeatureCard
          title="AI that answers questions for you, real-time"
          description="Uses screen + transcript + AI to answer questions live."
          image="/pagedemo1/ask-ai.jpg"
          variant="gradient"
          height="h-[400px] lg:h-[500px]"
        />

        <FeatureCard
          title="Instant follow-up emails"
          description="Send perfectly drafted emails within seconds."
          image="/pagedemo1/follow-up.jpg"
          height="h-[400px] lg:h-[500px]"
        />

        <FeatureCard
          title="Who are you really talking to?"
          description="Learn everything before every call."
          image="/pagedemo1/pre-call.jpg"
          height="h-[400px] lg:h-[330px]"
        />

        <FeatureCard
          title="Beautiful meeting notes"
          description="Instant shareable notes generated by AI."
          image="/pagedemo1/notes.jpg"
          height="h-[400px] lg:h-[330px]"
        />

      </div>
    </section>
  );
}